export const REQUEST_MESSAGES = 'REQUEST_MESSAGES';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';

export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const REQUEST_CHANNELS = 'REQUEST_CHANNELS';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const RECEIVE_CHANNELS = 'RECEIVE_CHANNELS';

export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

export const REGISTERING_USER = 'REGISTERING_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const JOINING_CHANNEL = 'JOINING_CHANNEL';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const JOIN_ERROR = 'JOIN_ERROR';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
