export const ADDING_MESSAGE = 'ADDING_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_ERROR = 'ADD_MESSAGE_ERROR';

export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const REQUEST_CHANNELS = 'REQUEST_CHANNELS';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const FETCH_CHANNELS_ERROR = 'FETCH_CHANNELS_ERROR';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';

export const ADDING_CHANNEL = 'ADDING_CHANNEL';
export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const ADD_CHANNEL_ERROR = 'ADD_CHANNEL_ERROR';

export const JOINING_CHANNEL = 'JOINING_CHANNEL';
export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const JOIN_ERROR = 'JOIN_ERROR';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';

export const REQUEST_USERS = 'REQUEST_USERS';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const AUTHENTICATING_USER = 'AUTHENTICATING_USER';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

export const REGISTERING_USER = 'REGISTERING_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
