export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_ERROR = 'ADD_MESSAGE_ERROR';
export const RECEIVE_MESSAGE_SUCCESS = 'RECEIVE_MESSAGE_SUCCESS';

export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const FETCH_CHANNELS_ERROR = 'FETCH_CHANNELS_ERROR';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';

export const ADD_CHANNEL_SUCCESS = 'ADD_CHANNEL_SUCCESS';
export const ADD_CHANNEL_ERROR = 'ADD_CHANNEL_ERROR';
export const RECEIVE_CHANNEL_SUCCESS = 'RECEIVE_CHANNEL_SUCCESS';

export const JOIN_ERROR = 'JOIN_ERROR';
export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const RECEIVE_MEMBER_SUCCESS = 'RECEIVE_MEMBER_SUCCESS';

export const SEND_INVITE_SUCCESS = 'SEND_INVITE_SUCCESS';
export const SEND_INVITE_ERROR = 'SEND_INVITE_ERROR';
export const RECEIVE_INVITE_SUCCESS = 'RECEIVE_INVITE_SUCCESS';

export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
